import pyautogui
from time import sleep
pyautogui.PAUSE = 2
pyautogui.moveTo(1294, 10, 1)
pyautogui.click()
sleep(1)
pyautogui.moveTo(40, 12, 1)
pyautogui.click()
sleep(1)
pyautogui.moveTo(107, 243, 1)
sleep(1)
pyautogui.moveTo(265, 269, 1)
pyautogui.click()
sleep(5)
pyautogui.moveTo(1219, 82, 1)
pyautogui.click()
sleep(10)
pyautogui.moveTo(957, 455, 1)
pyautogui.click()
sleep(1) 
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.press('enter')
sleep(1)
pyautogui.hotkey('alt', 'tab')
sleep(3)
