import pyautogui
from time import sleep
pyautogui.PAUSE = 2
sleep(1)
pyautogui.moveTo(42, 15, 1)
pyautogui.click()
sleep(1)
pyautogui.moveTo(42, 148, 1)
pyautogui.click()
sleep(5)
pyautogui.moveTo(1537, 118, 1)
pyautogui.click()
sleep(10)
pyautogui.moveTo(1310, 528, 1)
pyautogui.click()
sleep(1) 
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.write('1')
sleep(1)
pyautogui.press('enter')
sleep(1)
pyautogui.hotkey('alt', 'tab')
sleep(3)
